<footer>
  <p class="address">Bernie 2016<br>PO Box 905<br>Burlington, VT 05402</p>
  <p class="site-title">Paid for by Bernie 2016</p>
  <span class="billionaires">
  <svg viewBox="0 0 350 47"><use xlink:href="/img/billionaires.svg#billionaires"></use></svg>
  (not the billionaires)
  </span>
  <p><span class="copyright">© Bernie 2016</span> | <a href="http://www.berniesanders.com/privacy-policy">Privacy Policy</a></p>
</footer>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64649524-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
